### ISSUE TITLE
Missing details on how to generate association rules?

### ISSUE THREAD

**Issue by Autonom** [oghenejokpeme/RLCBkb#1]
I'm trying to generate the features used in the paper.  Is this workflow correct?

```
$ yap
?- [aleph, main].
?- read_all(networks).
?- induce_features.
```
Perhaps I've misunderstood how this should work because aleph reports
```
[cannot open] [networks.f]
[cannot open] [networks.n]
```
Are the .p and .n files available somewhere?

**Comment by oghenejokpeme** [comment]
Added the .f file. Everything should work now. Apologies.

**Comment by Autonom** [comment]
Many thanks for the prompt response.

I am still encountering two issues.  Firstly,
```
?- read_all(networks).
reconsulting networks.b...
reconsulted RLCBkb-master/networks.b in module user, 5 msec -3995360 bytes
[consulting pos examples] [networks.f]
[error] [set(skolemvars,0)]                                  <-- 
[cannot open] [networks.n]
true
```
Can the message `[error] [set(skolemvars,0)]` be safely ignored?

Secondly, I think there may be a missing predicate definition:
```
?- induce_features.
[select example] [1]
[sat] [1]
[networked(DB11745)]
          ** procedure user:comp_func_group('DB11745',_224,halide,_226) does not exist **
```
I couldn't find `comp_func_group/4` anywhere in the code base.

Context:
networks.b:92
```
has_group_count(Compound, Group, Count):-
    compound_id(Compound),
    has_functional_group(Compound, Group),
    findall(Group, comp_func_group(Compound, _, Group, _), Ans),
    length(Ans, Count).
```

**Comment by oghenejokpeme** [comment]
Issue 1.
I don't get that error, might it be a problem with your version of Aleph? That said, I think it can be safely ignored.

Issue 2.
Updated the repository. Again, apologies for this. The has_group_count/3 and has_ring_count/3 predicates in the networks.b file are from a time were we generated the information during rule search (much slower than the correct form). However, this is all available in pharmacophores/group_count.pl and pharmacophores/group_ring.pl. We did this so users won't have to generate them themselves.

**Comment by Autonom** [comment]
That's it, I'm getting the association rules out now.  Thanks again for your help.

The rule bodies appear to be mainly (all?) drug properties: has_functional_group, has_group_count, etc.  Yet the hypothesis space has many other predicates that do not appear.
```
:- modeb(1, drug_drug_(+drug, -drug)).
:- modeb(1, drug_disease(+drug, -disease)).
:- modeb(1, disease_function(+disease, -function)).
:- modeb(*, drug_gene(+drug, -gene)).
:- modeb(*, gene_function(+gene, -function)).
:- modeb(*, has_functional_group(+drug, #group)).
:- modeb(*, has_ring(+drug, #ringtype)).
:- modeb(*, has_group_count(+drug, #group, #count)).
:- modeb(*, has_ring_count(+drug, #ringtype, #count)).
:- modeb(*, has_group_ring_attachment(+drug, #group, #ringtype)).
:- modeb(*, is_a(+function, #function)).
:- modeb(*, part_of(+function, #function)).
:- modeb(*, has_part(+function, #function)).
:- modeb(*, regulates(+function, #function)).
:- modeb(*, neg_regulates(+function, #function)).
:- modeb(*, pos_regulates(+function, #function)).
```
Because of this, I'm concerned that I am not obtaining the same rules as reported in the paper.  Would you be able to share your rules so I can verify my results?

Rules I obtained: [learned_features.txt](https://github.com/oghenejokpeme/RLCBkb/files/6754908/learned_features.txt)

**Comment by oghenejokpeme** [comment]
I've pushed further updates to the repository. The reason some of the predicates were missing from your rules was because the main.pl file in the root folder wasn't getting loaded (see updates in networks.b). You should now get similar rules to those in the learned_rules.txt file in the repository.
